### PR TITLE
Rewrite critical part

### PR DESCRIPTION
**Pull request by IurmanJ**
Make this important part easier to read/understand

### CODE REVIEW

**Review by evyncke — COMMENTED** [review]
If RFC 9116 allows for multiple lines field, then in the example make it multi-line and refers to JAMES ;-)

**Comment by IurmanJ** [comment]
> If RFC 9116 allows for multiple lines field, then in the example make it multi-line and refers to JAMES ;-)

RFC 9116 considers that a field (line) ends with a CRLF. So either we have the following:

```diff
-        Description: This is the description of the measurement
+        Description: This is a description of the measurement. For instance, the in-band probe attribution was used by [I-D.draft-vyncke-v6ops-james].
```

Or we specify that the "Description" field can be multiline and have the following:

```diff
-        Description: This is the description of the measurement
+        Description: This is a multiline description of the measurement.
+                     For instance, the in-band probe attribution was used
+                     by [I-D.draft-vyncke-v6ops-james].
```

Pros: this document introduces it, so we can specify it. Cons: doesn't match RFC 9116's grammar, which is not good.

Thoughts? I'd go for the first IMHO (which is equal to a -very long- line, not a multiline).

**Comment by IurmanJ** [comment]
I just added a commit on top of the PR to address your comment.

**Comment by evyncke** [comment]
Let's keep it simple, i.e., no multi-line then to keep RFC 9116 syntax but you can still add the JAMES I-D reference in the example (this will be a long line though but this is OK)

**Comment by IurmanJ** [comment]
All right, should be good now :-)

**Review by evyncke — APPROVED** [review]

**Pull request merged**
